// include/kits/fonts.h
#pragma once
// 添加Font Awesome图标加载范围的定义
#define ICON_MIN_FA 0xe005
#define ICON_MAX_FA 0xf8ff

// Font Awesome 6 Free-Solid-900 图标宏定义
#define ICON_FA_EYE          "\uf06e"   // 眼睛图标 (查看/预览)
#define ICON_FA_EDIT         "\uf044"   // 编辑图标 (修改内容)
#define ICON_FA_SEARCH       "\uf002"   // 搜索图标 (查找功能)
#define ICON_FA_UNDO         "\uf0e2"   // 撤销图标 (恢复操作)
#define ICON_FA_ARROW_RIGHT  "\uf061"   // 右箭头图标 (前进/下一步)
#define ICON_FA_ARROW_LEFT   "\uf060"   // 左箭头图标 (后退/上一步)
#define ICON_FA_TRASH        "\uf1f8"   // 垃圾桶图标 (删除项目)
#define ICON_FA_CLONE        "\uf24d"   // 克隆图标 (复制/重复)
#define ICON_FA_SAVE         "\uf0c7"   // 保存图标 (存储/下载)
#define ICON_FA_GAMEPAD      "\uf11b"   // 游戏手柄图标 (游戏控制)
#define ICON_FA_VOLUME_UP    "\uf028"   // 音量增加图标 (声音控制)
#define ICON_FA_IMAGE        "\uf03e"   // 图片图标 (图像/照片)
#define ICON_FA_KEYBOARD     "\uf11c"   // 键盘图标 (输入设备)
#define ICON_FA_INFO_CIRCLE  "\uf05a"   // 信息圆圈图标 (详情/帮助)
#define ICON_FA_GEAR         "\uf013"   // 齿轮/设置图标 (配置选项)
#define ICON_FA_FOLDER_OPEN  "\uf07c"   // 打开的文件夹图标 (目录浏览)
#define ICON_FA_FOLDER       "\uf07b"   // 文件夹图标 (文件目录)
#define ICON_FA_CHECK_CIRCLE "\uf058"   // 勾选圆圈图标 (确认/成功)
#define ICON_FA_CHECK        "\uf00c"   // 勾选图标 (已选中/已选择)
#define ICON_FA_CHEVRON_UP   "\uf077"   // 向上箭头图标 (展开/打开)
#define ICON_FA_CHEVRON_DOWN "\uf078"   // 向下箭头图标 (收起/关闭)
#define ICON_FA_CHEVRON_LEFT "\uf053"   // 向左箭头图标 (返回/上一页)
#define ICON_FA_CHEVRON_RIGHT "\uf054" // 向右箭头图标 (前进/下一页)
#define ICON_FA_PLUS         "\uf067"   // 加号图标 (添加/创建)
#define ICON_FA_MINUS        "\uf068"   // 减号图标 (删除/取消)
#define ICON_FA_TIMES        "\uf00d"   // 乘号图标 (关闭/结束)
#define ICON_FA_HOME         "\uf015"   // 首页图标 (主页/主菜单)
#define ICON_FA_USER         "\uf007"   // 用户图标 (个人信息)
#define ICON_FA_USERS        "\uf0c0"   // 用户组图标 (用户管理)
#define ICON_FA_USER_PLUS    "\uf234"   // 添加用户图标 (添加新用户)
#define ICON_FA_USER_MINUS   "\uf235"   // 删除用户图标 (删除用户)
#define ICON_FA_USER_CHECK   "\uf236"   // 勾选用户图标 (选择用户)
#define ICON_FA_USER_EDIT    "\uf237"   // 编辑用户图标 (修改用户信息)
#define ICON_FA_USER_TIMES   "\uf238"   // 关闭用户图标 (删除用户)
#define ICON_FA_USERS_COG    "\uf0c5"   // 用户设置图标 (用户权限管理)
#define ICON_FA_COGS         "\uf085"   // 齿轮图标 (设置/配置)
#define ICON_FA_COG          "\uf013"   // 齿轮/设置图标 (配置选项)
#define ICON_FA_WRENCH       "\uf0ad"   // 扳手图标 (设置/工具)
#define ICON_FA_CALENDAR     "\uf073"   // 日历图标 (日期/计划)
#define ICON_FA_CALCULATOR   "\uf1ec"   // 计算器图标 (计算器)
#define ICON_FA_BELL         "\uf0f3"   // 铃铛图标 (提醒/通知)
#define ICON_FA_BELL_SLASH   "\uf1f6"   // 关闭铃铛图标 (取消提醒)
#define ICON_FA_BELL_RINGING "\uf1f6"   // 响铃铃铛图标 (提醒)
#define ICON_FA_BELL_O       "\uf0a2"   // 闪烁铃铛图标 (警告)
#define ICON_FA_BELL_DOVE    "\uf1e6"   // 鸟铃图标 (鸟叫)
#define ICON_FA_BELL_EXCITED "\uf1f4"   // 心情高昂铃铛图标 (激动)
#define ICON_FA_BELL_SLASH_O "\uf1f7"   // 关闭闪烁铃铛图标 (取消警告)
#define ICON_FA_BELL_RINGING_O "\uf1f7" // 响铃闪烁铃铛图标 (警告)
#define ICON_FA_FILE              "\uf15b"   // 文件图标 (文档/文件)
#define ICON_FA_FILE_CIRCLE_PLUS  "\ue494"   // 带加号的文件图标 (添加文件/新建文档)
#define ICON_FA_FLOPPY_DISK       "\uf0c7"   // 软盘图标 (保存/存储设备) 与 ICON_FA_SAVE 相同
#define ICON_FA_POWER_OFF         "\uf011"   // 电源关闭图标 (关机/退出)
#define ICON_FA_CIRCLE_QUESTION   "\uf059"   // 问号圆圈图标 (帮助/疑问)
#define ICON_FA_BOOK              "\uf02d"   // 书籍图标 (文档/手册)
#define ICON_FA_DIAGRAM_PROJECT   "\uf542"   // 项目图图标 (项目结构/流程图)
#define ICON_FA_PLAY              "\uf04b"   // 播放图标 (开始/运行)
