// include/mainProgramInc.h

#pragma once
// kits模块
#include "kits/imgui.h"
#include "kits/streams.h"
#include "kits/strings.h"
// core模块
#include "core/window.h"
#include "core/inputs.h"
// graphics模块
#include "graphics/renderer.h"
#include "graphics/shader.h"
// resources模块
#include "resources/model.h"
// loaders模块
#include "loaders/model.h"
#include "loaders/texture.h"
#include "loaders/resource.h"
// ui模块
#include "ui/uiMng.h"